/**
 * Users Service
 * <a href=\"/swagger-json\">Open API Schema</a>
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Photo } from './photo';


export interface User { 
    id: string;
    firstName: string;
    lastName: string;
    age: number;
    photos: Array<Photo>;
}

