/**
 * Users Service
 * <a href=\"/swagger-json\">Open API Schema</a>
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Photo } from './photo';

export class User {
    'id': string;
    'firstName': string;
    'lastName': string;
    'age': number;
    'photos': Array<Photo>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "age",
            "baseName": "age",
            "type": "number"
        },
        {
            "name": "photos",
            "baseName": "photos",
            "type": "Array<Photo>"
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
}

