apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-users
spec:
  selector:
    matchLabels:
      app: service-users
  replicas: 1
  template:
    metadata:
      labels:
        app: service-users
    spec:
      containers:
      - name: service-users
        image: localhost:5000/service-users:${VERSION}
        ports:
        - containerPort: 3333
        env:
          - name: port
            value: "3333"
          - name: database
            value: "database"
          - name: serviceMoviesHost
            value: "service-movies"
          - name: serviceMoviesPort
            value: "3334"
