apiVersion: batch/v1
kind: Job
metadata:
  name: service-users-migration
spec:
  template:
    spec:
      containers:
      - name: service-users-migration
        image: localhost:5000/service-users-migration:$VERSION
        command: ["npm", "run", "typeorm:migration:run"]
      restartPolicy: Never
  backoffLimit: 4
  