apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mariadb
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
          - name: MYSQL_DATABASE
            value: "my-test"
          - name: MYSQL_USER
            value: "my-test"
          - name: MYSQL_PASSWORD
            value: "password"
        ports:
        - containerPort: 3306
