apiVersion: v1
kind: Pod
metadata:
  name: logstash
spec:
  containers:
  - name: logstash
    image: localhost:5000/logstash:$VERSION
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always