registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /cert/server.crt
    REGISTRY_HTTP_TLS_KEY: /cert/server.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - ~/.registry/data:/var/lib/registry
    - ~/.registry/cert:/cert
    - ~/.registry/auth:/auth