apiVersion: v1
kind: Pod
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: development
spec:
  containers:
  - image: localhost:5000/logstash:29
    imagePullPolicy: IfNotPresent
    name: logstash
  restartPolicy: Always
